newscoop_example_plugin:
    resource: "@NewscoopExamplePluginBundle/Controller/"
    type:     annotation
    prefix:   /

gimme:
    type: rest
    prefix: /api
    resource: "@NewscoopGimmeBundle/Resources/config/routing.yml"