language: php
php:
  - 5.3

branches:
  only:
    - next

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install libzend-framework-php

before_script:
  - ./scripts/ci/before_script.sh
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit --configuration newscoop/tests/phpunit.xml
