language: php
php:
  - "5.4"
  - "5.3"
notifications:
  email: false
before_script:
  - "cp -r dependencies/include/* newscoop/include/"
  - cd newscoop/
  - php composer.phar self-update
  - php composer.phar install
  - php scripts/doctrine.php
