newscoop:
    extends:
        file: scripts/docker/docker-newscoop.yml
        service: newscoop
    links:
        - mysql
    environment:
        - APPLICATION_ENVIRONMENT=dev

mysql:
    extends:
        file: scripts/docker/docker-newscoop.yml
        service: mysql

