parameters:
    admin:
        resources:
            acl:
                cache: "Doctrine\Common\Cache\ArrayCache"
    doctrine:
        cache: "Doctrine\Common\Cache\ArrayCache"
    phpSettings:
        display_startup_errors: "1"
        display_errors: "1"
    resources:
        frontController:
            params:
                displayExceptions: "1"
    session:
        cookie_domain: ""
    newscoop.eventDispatcher.class: "Newscoop\\EventDispatcher\\TraceableEventDispatcher"
