services:
    newscoop_newscoop.routing.loader.plugins:
        class: Newscoop\NewscoopBundle\Routing\PluginsLoader
        arguments: ["@plugins.manager", "@service_container"]
        tags:
            - { name: routing.loader }

parameters:
    smarty.extension.routing.class: "Newscoop\\NewscoopBundle\\Extension\\RoutingExtension"