framework:
    secret:          sadfdsfgdsgfgdsfgdsfgdsfger3ewtr
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    trust_proxy_headers:  false