Newscoop\Entity\Snippet\SnippetTemplate:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            read_only: true
            type: integer
            groups: ["details", "list"]
            serialized_name: id
        name:
            expose: true
            read_only: true
            type: string
            groups: ["details", "list"]
            serialized_name: name
        template:
            expose: true
            read_only: true
            type: string
            groups: ["details", "list"]
            serialized_name: template