services:
	articles.hooks.listener:
        class: "Newscoop\ArticlesBundle\EventListener\HookListener"
        arguments: ["@templating"]
        tags:
          - { name: kernel.event_listener, event: newscoop_admin.interface.articles.editorialcomments, method: listEditorialComments }