Newscoop\Entity\Article:
    exclusion_policy: ALL
    properties:
        number:
            expose: true
            read_only: true
            type: string
            groups: ["list", "details"]
            serialized_name: number
        name:
            expose: true
            read_only: true
            type: string
            groups: ["list", "details"]
            serialized_name: title
        date:
            expose: true
            read_only: true
            type: datetime
            groups: ["list", "details"]
            serialized_name: updated
        published:
            expose: true
            read_only: true
            type: string
            groups: ["list", "details"]
            serialized_name: published
        articleAuthors:
            expose: true
            read_only: true
            type: author
            groups: ["list", "details"]
            serialized_name: authors
        comments_link:
            expose: true
            read_only: true
            type: string
            groups: ["list", "details"]
            type: comments_link
            serialized_name: comments
