Newscoop\Entity\Article:
    exclusion_policy: ALL
    properties:
        number:
            expose: true
            read_only: true
            type: string
            serialized_name: number
        name:
            expose: true
            read_only: true
            type: string
            serialized_name: title
        date:
            expose: true
            read_only: true
            type: datetime
            serialized_name: updated
        published:
            expose: true
            read_only: true
            type: string
            serialized_name: published
        articleAuthors:
            expose: true
            read_only: true
            type: author
            serialized_name: authors
