services:
    comment:
        class:      Newscoop\Services\CommentService
        arguments:  ["@em"]
        tags:
            -  { name: event_listener, event: comment.create, method: update }
            -  { name: event_listener, event: comment.update, method: update }
            -  { name: event_listener, event: comment.recommended, method: update }
            -  { name: event_listener, event: comment.delete, method: update }