services:
    user_attributes:
        class:      Newscoop\Services\UserAttributeService
        arguments:  ["@em"]
        tags:
            -  { name: event_listener, event: image.delivered, method: update }
            -  { name: event_listener, event: image.approved, method: update }
            -  { name: event_listener, event: image.published, method: update }
            -  { name: event_listener, event: document.delivered, method: update }
            -  { name: event_listener, event: document.approved, method: update }